### ISSUE TITLE
Question on the code

### ISSUE THREAD

**Issue by FritzPeleke** [gerdos/PyRAMA#2]
Hi for a project in school i have to produce a Ramachandran code for python. I have been trying to follow your code but I can't really put the pieces together. For example, what does the _cache_RAMA_PREF_VALUES() actually do? what are is the use of the .data files (general, gly, pro, prepro)

**Comment by gerdos** [comment]
Dear FritzPeleke!

The data folder contains all the Ramachandran preferences for torsion angles. The general file contains the "general cases". In case our residue is a glycine, the torsion angle preferences will be different, so there is a separate file for that. Prolines too have a different preference, and the residue before a proline has different than general preferences as well. 

For more information about how these preferences were calculated you can read this article: Lovell et al. Structure validation by Calpha geometry: phi,psi and Cbeta deviation. 2003; DOI: 10.1002/prot.10286

The `_cache_RAMA_PREF_VALUES()` function just reads the preference values from these files, and transforms the data into a form which can be plotted. This is basically the background you can see in each plot, which tells you where the dots should be.

**Comment by FritzPeleke** [comment]
Hi @gerdos, 
Thank you for the information and your work is really good. I tried using the raw code instead of the package and when I run the code there seem to be a problem with the calling of “global RAMA_PREF_VALUES”. I had to call global before 
the if statement not after it for example. And I don’t know why but I installed the package and when I tried importing it it didn’t appear on Pycharm. So I used the raw code directly and tried to modify it. But thanks all thesame for the work. It’s brilliant

**Comment by gerdos** [comment]
This is an old code, and it has been forked, I will try to look into the errors when I get home.

Thanks :)

**Comment by gerdos** [comment]
I pushed a new version where I corrected the error of the global declaration.

**Comment by sagarhm** [comment]
plot_ramachandran() missing 1 required positional argument: 'outliers'

how to fix these error from ur code plzz can u help me

**Comment by gerdos** [comment]
The function requires an argument containing the outliers.

Saga032000 <notifications@github.com> ezt írta (időpont: 2020. jún. 11.,
Csü 17:20):

**Comment by sagarhm** [comment]
sir  how to get plot like thesse image which mention below from ur code plzzz help 
![download (1)](https://user-images.githubusercontent.com/55372566/84468241-f47d9280-ac9b-11ea-8c01-d09e2d27a7fd.jpg)
when i done i got these plot ...
![IMG_20200610_180335](https://user-images.githubusercontent.com/55372566/84468467-85ed0480-ac9c-11ea-8e0a-cfecb3afce87.jpg)

**Comment by gerdos** [comment]
As the allowed area on this picture is different, you would need to code
that oart. For the colors, just change the color values

Saga032000 <notifications@github.com> ezt írta (időpont: 2020. jún. 12.,
Pén 7:31):

**Comment by sagarhm** [comment]
sir how to change colours values

**Comment by bb2n18** [comment]
Hi,

How can one edit ramachandran plot in Pyrama? As to change the values on axis?
I would like to have markers for 0, 90 and 180 degrees on both axis. For now I get 0, 50 and 100 degrees on Y and only 0 and 100 degrees on X. I have looked in preferences but could not find that option.
Many thanks for your help

**Comment by gerdos** [comment]
> Hi,
> 
> How can one edit ramachandran plot in Pyrama? As to change the values on axis?
> I would like to have markers for 0, 90 and 180 degrees on both axis. For now I get 0, 50 and 100 degrees on Y and only 0 and 100 degrees on X. I have looked in preferences but could not find that option.
> Many thanks for your help

PyRama uses the `matplotlib` plotting library, you can set y and x tick labels with the their respective methods described here: https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set_yticklabels.html#matplotlib.axes.Axes.set_yticklabels
